name: orange
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rust_builder:
    path: rust_builder
  flutter_rust_bridge: 2.6.0
  freezed_annotation: ^2.4.4
  
  image_picker: ^1.1.2
  window_manager: ^0.4.3
  intl: ^0.17.0
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.3
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  flutter_svg: ^2.0.10+1
  custom_qr_generator: ^0.1.2
  http: ^1.2.1
  zxing_lib: ^0.6.0
  shared_preferences: ^2.3.2
  thread: ^0.2.2
  uuid: ^3.0.7
  orangeme_material:
    path: './orangeme_material'
  flutter_local_notifications: ^18.0.1
  workmanager: ^0.5.2
  share_plus: ^10.1.2
  flutter_vibrate: ^1.3.0
  vibration: ^2.0.1
  tuple: ^2.0.2
  loop_page_view: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/mockups/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900
  